#pragma once

#include <string>

#include "game/interfaces/imaterial.hpp"
#include "utils/image.hpp"

namespace Game
{
    /**
     * @brief Texture-backed wall material loaded from an image file.
     *
     * The sampled color comes from the internal Utils::Image according to the
     * projected texture coordinates generated by the renderer.
     */
    class TextureMaterial : public IMaterial
    {
    public:
        TextureMaterial(const std::string &filename);

        virtual MaterialDescriptor getDescriptor() const override;
        virtual MaterialSample
        getSample(const Math::Point2 &texCoord = Math::Point2(0.0f, 0.0f)) const override;

    private:
        Utils::Image texture;
    };
} // namespace Game
